 * Serving Flask app 'main.py'
 * Debug mode: on
Address already in use
Port 8080 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'main.py'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.128.0.3:8080
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 113-254-234
24.184.11.255 - - [14/Feb/2025 20:22:47] "[35m[1mGET /add/100/34 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/agodbole/csc330/.venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agodbole/csc330/.venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agodbole/csc330/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agodbole/csc330/.venv/lib/python3.11/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agodbole/csc330/.venv/lib/python3.11/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agodbole/csc330/.venv/lib/python3.11/site-packages/flask/app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a int.
24.184.11.255 - - [14/Feb/2025 20:22:47] "GET /add/100/34?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
24.184.11.255 - - [14/Feb/2025 20:22:47] "GET /add/100/34?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
24.184.11.255 - - [14/Feb/2025 20:22:47] "GET /add/100/34?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/agodbole/csc330/code/weather/activity-2/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 113-254-234
24.184.11.255 - - [14/Feb/2025 20:23:35] "GET /add/100/34 HTTP/1.1" 200 -
